services:

  # PHP + Apache
  php:
    build: .
    container_name: ecoride_web
    ports:
      - "8080:80"   # Accès direct à Apache pour les tests
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      # Monte ton vhost custom pour pointer vers /public
      - ./apache/default.conf:/etc/apache2/sites-available/000-default.conf:ro
    depends_on:
      - db
      - mongo
    environment:
      DB_HOST: db
      DB_NAME: ecoride
      DB_USER: ecoride_user
      DB_PASS: ecoride_password
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: ecoride
    # Active mod_rewrite + (ré)active le site, puis démarre Apache
    command: bash -lc "a2enmod rewrite headers && a2ensite 000-default && apache2-foreground"
    networks:
      - ecoride_network

  # Nginx en reverse proxy
  nginx:
    image: nginx:alpine
    container_name: dev_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./public:/var/www/html/public:ro
    depends_on:
      - php
    networks:
      - ecoride_network

  # Base de données MySQL
  db:
    image: mysql:8.0
    container_name: ecoride_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecoride
      MYSQL_USER: ecoride_user
      MYSQL_PASSWORD: ecoride_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - ecoride_network

  # Interface phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecoride_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ecoride_user
      PMA_PASSWORD: ecoride_password
      PMA_ROOT_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - ecoride_network

  # Base NoSQL MongoDB
  mongo:
    image: mongo:7
    container_name: ecoride_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ecoride_network

networks:
  ecoride_network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
